config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  resource :dashboard

  resources :books, except: [:destroy]

  root to: 'dashboards#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  validates :title, presence: true, uniqueness: { scope: :user }

  belongs_to :user



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable, :registerable, :recoverable, :trackable, :validatable
  devise :database_authenticatable, :registerable,  :rememberable

  has_many :books

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  respond_to :js, :html
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update]

  def index
    @books = current_user.books
  end

  def show
  end

  def new
    @book = current_user.books.new
  end

  def create
    @book = current_user.books.create book_params
    respond_with @book
  end

  def edit
  end

  def update
    @book.update(book_params)
    respond_with @book
  end

  private

  def book_params
    params.require(:book).permit(:title)
  end

  def set_book
    @book = current_user.books.find(params[:id])
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  def show
  end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.slim
= form_for @book do |builder|
  - if @book.errors.present?
    .row
      .col.s12.red-text.center-align
        = @book.errors.full_messages

  .row
    .input-field.col.s6
      label[for='book_title'] Title
      = builder.text_field :title

  .row
    .col.s6
      = builder.submit 'Submit', class: 'btn'

app/views/books/edit.html.slim
.row
  .col.s12
    = render partial: 'form'

app/views/books/index.html.slim
.row

  - @books.each do |book|
    .col.s12.m4
      = link_to book_path(book) do
        .card-panel
          span= book.title

  .col.s12.m4
    = link_to new_book_path do
      .card-panel.teal
        span.white-text Add New

app/views/books/new.html.slim
.row
  .col.s12
    = render partial: 'form'

app/views/books/show.html.slim
.row
  .col.m2
  .col.s12.m6
    h3 = @book.title
  .col.m4.links
    ul
      li
        = link_to 'Edit', edit_book_path(@book)

.divider

.row
  

app/views/layouts/_header.html.slim
.navbar-fixed
  nav
    .nav-wrapper
      = link_to root_path, class: 'brand-logo center' do
        = t(:service_name)
      ul.left.hide-on-med-and-down
        = render partial: 'layouts/nav_links'

      - if signed_in?
        .right.hide-on-med-and-down
          ul
            li.username
              = current_user.username
            li.links
              = link_to 'Logout', destroy_user_session_path, method: :delete


        a.button-collapse[href='#' data-activates='mobile-side-nav']
          i.material-icons menu
        ul.side-nav#mobile-side-nav
          .userView
            .name.blue-text= current_user.username
            .links
              = link_to 'Logout', destroy_user_session_path, method: :delete
          .divider
          = render partial: 'layouts/nav_links'

app/views/layouts/_nav_links.html.slim
- if current_user
  li class=('active' if current_page?(controller: :books))
    = link_to 'Books', books_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title= t(:service_name)
    meta name='viewport' content='width=device-width, initial-scale=1.0'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = stylesheet_link_tag 'https://fonts.googleapis.com/icon?family=Material+Icons'
    = csrf_meta_tags

  body
    = render partial: 'layouts/header'

    .row
      .col.m1
      .col.m10.s12.viewport
        = yield
      .col.m1

app/views/users/shared/_links.html.slim
- if controller_name != 'sessions'
  = link_to 'Log in', new_session_path(resource_name)
  br
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to 'Sign up', new_registration_path(resource_name)
  br